"""Closed v0 type families; enum values are data, never issuance authority."""

from enum import Enum


class AssertionBasis(Enum):
    FORMAL_GIVEN = "FORMAL_GIVEN"
    FORMAL_ASSUMPTION = "FORMAL_ASSUMPTION"
    EXTERNAL_OBSERVATION = "EXTERNAL_OBSERVATION"
    INTERNAL_RETRIEVAL = "INTERNAL_RETRIEVAL"
    HYPOTHETICAL = "HYPOTHETICAL"
    PREDICTION_VIEW = "PREDICTION_VIEW"
    CAUSAL_RESULT_VIEW = "CAUSAL_RESULT_VIEW"
    DERIVED = "DERIVED"


class DependencyKind(Enum):
    ASSUMPTION = "ASSUMPTION"
    HYPOTHESIS = "HYPOTHESIS"
    PREDICTION = "PREDICTION"
    CAUSAL_RESULT = "CAUSAL_RESULT"
    INTERNAL_RETRIEVAL = "INTERNAL_RETRIEVAL"


class InvocationState(Enum):
    ACTIVE = "ACTIVE"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"


class BudgetSourceKind(Enum):
    INVOCATION_GENERAL = "INVOCATION_GENERAL"
    FORECAST_ESCROW = "FORECAST_ESCROW"
    CAUSAL_STUDY_ESCROW = "CAUSAL_STUDY_ESCROW"


class WorkEffectClass(Enum):
    PURE_COMPUTE = "PURE_COMPUTE"
    OPERATIONAL_EFFECT = "OPERATIONAL_EFFECT"


class ForecastStatus(Enum):
    PENDING = "PENDING"
    MATCHED = "MATCHED"
    WINDOW_ELAPSED_WITHOUT_MATCH = "WINDOW_ELAPSED_WITHOUT_MATCH"
    INCONCLUSIVE_OBSERVATION_GAP = "INCONCLUSIVE_OBSERVATION_GAP"
    TARGET_STALE = "TARGET_STALE"
    BOUNDARY_TERMINATED = "BOUNDARY_TERMINATED"
    CANCELLED = "CANCELLED"
    ENVIRONMENT_STALE = "ENVIRONMENT_STALE"


class CaptureState(Enum):
    CAPTURED = "CAPTURED"
    PROVEN_EMPTY = "PROVEN_EMPTY"
    OBSERVATION_GAP = "OBSERVATION_GAP"


class FailureCode(Enum):
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_FORMAL_AUTHORITY = "INVALID_FORMAL_AUTHORITY"
    INVALID_DEPENDENCY = "INVALID_DEPENDENCY"
    INVALID_SCOPE = "INVALID_SCOPE"
    INVALID_POLICY_BINDING = "INVALID_POLICY_BINDING"
    ENVIRONMENT_STALE = "ENVIRONMENT_STALE"
    INVOCATION_NOT_ACTIVE = "INVOCATION_NOT_ACTIVE"
    CIE_STALE = "CIE_STALE"
    OWNER_AUTHORITY_STALE = "OWNER_AUTHORITY_STALE"
    BUDGET_ABORT = "BUDGET_ABORT"
    CAPACITY_ABORT = "CAPACITY_ABORT"
    PARTIAL_BUDGET = "PARTIAL_BUDGET"
    CONSTRAINT_CHECK_INCOMPLETE = "CONSTRAINT_CHECK_INCOMPLETE"
    CONSTRAINT_CHECK_STALE = "CONSTRAINT_CHECK_STALE"
    STALE_CONSTRAINT_CLEARANCE = "STALE_CONSTRAINT_CLEARANCE"
    PARENT_AUTHORITY_STALE = "PARENT_AUTHORITY_STALE"
    OPERATIONAL_EFFECT_AUTHORITY_STALE = "OPERATIONAL_EFFECT_AUTHORITY_STALE"
    EFFECT_PAYLOAD_MISMATCH = "EFFECT_PAYLOAD_MISMATCH"
    MISSING_BUDGET_CHARGE = "MISSING_BUDGET_CHARGE"
    AMBIGUOUS_BUDGET_OWNER = "AMBIGUOUS_BUDGET_OWNER"
    BUDGET_WORKCLASS_MISMATCH = "BUDGET_WORKCLASS_MISMATCH"
    UNKNOWN_OPERATION_TYPE = "UNKNOWN_OPERATION_TYPE"
    EXEMPTION_CONTRACT_VIOLATION = "EXEMPTION_CONTRACT_VIOLATION"
    CROSS_CAPABILITY_AUTHORITY_LEAK = "CROSS_CAPABILITY_AUTHORITY_LEAK"
    CROSS_CAPABILITY_ADAPTER_TYPE_VIOLATION = "CROSS_CAPABILITY_ADAPTER_TYPE_VIOLATION"
    INTERNAL_CONTRACT_VIOLATION = "INTERNAL_CONTRACT_VIOLATION"
